
cache:
    directories:
        - '$HOME/.composer/cache'

matrix:
    fast_finish: true
    include:
        -
            os: 'linux'
            sudo: false
            language: 'php'
            php: '7.1'
        -
            os: 'linux'
            sudo: false
            language: 'php'
            php: '7.2'
#        -
#            os: 'osx'
#            language: 'generic'

before_install:
    - 'export COMPOSER_NO_INTERACTION=1'
    - 'export COMPOSER_DISABLE_XDEBUG_WARN=1'
    - 'export BREW_PHP=php71'
    - 'src-dev/scripts/travis/before_install.sh'

install:
    - 'composer install --no-progress'

script:
    - './bin/robo --ansi lint'
    - './bin/robo --ansi test'

after_success:
    - 'bash <(curl -s https://codecov.io/bash)'

notifications:
    email: false
